/*
 * This file is generated by jOOQ.
 */
package jooq_practice;


import java.util.Arrays;
import java.util.List;

import jooq_practice.tables.Users;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqPractice extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooq_practice</code>
     */
    public static final JooqPractice JOOQ_PRACTICE = new JooqPractice();

    /**
     * The table <code>jooq_practice.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private JooqPractice() {
        super("jooq_practice", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Users.USERS
        );
    }
}
