/*
 * This file is generated by jOOQ.
 */
package jooq_practice;


import jooq_practice.tables.Users;


/**
 * Convenience access to all tables in jooq_practice.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq_practice.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
